on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
  pull_request:

name: Continuous integration

jobs:
  run-tests:
    name: Check Building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Mypy
        run: pip3 install mypy
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      - uses: Swatinem/rust-cache@v1
      - name: Build
        run: rustc -o cleoqua cleoqua.rs
      - name: Clippy
        run: clippy-driver -D warnings cleoqua.rs
      - name: Mypy test.py
        run: mypy test.py

  check-fmt:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
      - uses: Swatinem/rust-cache@v1
      - name: Check Formatting
        run: rustfmt --check cleoqua.rs
